Repository untoc-camp/PlacePlanPlatform, pull requests merged in 2024-05, with the labels that each got.

#24 헤더 중간 제작
  component/header.py
  static/header_logo.png
  static/img/Logo.png
  static/img/logo_with_text.png
Labels: Feature

#26 달력 월 이동시 선택 UI 안보이는 버그
  element/calendar.py
Labels: bug

#28 헤더 인덱스 범위 수정
  element/header.py
Labels: bug

#30 헤더 요소 변경 #29
  element/header.py
Labels: Desigin

#32 user 데이터 클래스 제작 및 헤더 변경
  element/header.py
  model/user_model.py
  provider/user_api.py
  route/time_promise_route.py
  service/user_service.py
  static/api.py
  view/time_promise/time_promise_make_view.py
Labels: Feature

#34 시간 약속 메인 페이지
  element/week.py
  view/time_promise/time_promise_main_view.py
Labels: Feature, Desigin

#38 시간약속 리스트 수정
  element/header.py
  statics/header_logo.svg
  view/time_promise/time_promise_main_view.py
Labels: Feature, Desigin
